FROM node:22-alpine

# Install Python and its dependencies
RUN apk --update add --no-cache python3 curl

# RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /app

COPY package*.json ./

# Instala as dependências do projeto (incluindo devDependencies)
RUN npm install

COPY . .