### sem proxy
# @api=http://localhost:4010
### com proxy habilitado
@api=http://localhost/api/auth 

### Teste Geral
GET {{api}}/

### LOGIN
POST {{api}}/login
Content-Type: application/json

{
  "email": "vargas.lidio@gmail.com",
  "password": "ojupitas"
}

### LOGOUT
POST {{api}}/logout

### SignUp
POST {{api}}/signup
Content-Type: application/json

{
  "name": "ruanss",
  "email": "ruan@marcozs.com",
  "password": "senha"
}

### FORGOT PASSWORD
POST {{api}}/forgot-password
Content-Type: application/json

{
  "email": "vargas.lidio@gmail.com"
}

### VERIFY RESET TOKEN -- SUCCESS
GET {{api}}/verify-reset-token/9d065cec6f58dbdf53f00fa35c78898b048309c49c0ee8c239de62494d15e86f6c6a4f6a6c6e8c8099905d175bc96d480c1db0733181f4ea1a12f6c111c258eb

### VERIFY RESET TOKEN -- ERROR: invalid
GET {{api}}/verify-reset-token/abc


### RESET PASSWORD ---  SUCCESS: ALL VALID
PATCH {{api}}/reset-password
Content-Type: application/json

{
  "token": "9d065cec6f58dbdf53f00fa35c78898b048309c49c0ee8c239de62494d15e86f6c6a4f6a6c6e8c8099905d175bc96d480c1db0733181f4ea1a12f6c111c258eb",
  "password": "blableblibloblu",
  "passwordConfirm": "blableblibloblu"
}
